### ISSUE TITLE
spec files are not generated for new features or components

### ISSUE THREAD

**Issue by dougrchamberlain** [Aleksion/generator-angular-webpack-babel#6]
run `yo angular-webpack-starter:feature login`

expect login.spec.js to be created

result login.spec.js is not generated.

I'd be happy to contribute to resolve this issue your generator is incredibly close to my setup.

**Comment by Aleksion** [comment]
Hi @dougrchamberlain 

I haven't updated the generator in quite a while. So please feel free to contribute to it. 
But you're correct. It isn't currently adding the spec files automatically. Which is obviously bad practice on my part!

**Comment by Aleksion** [comment]
Hi @dougrchamberlain  - Did you ever get around to it?
