### ISSUE TITLE
$locationProvider.html5Mode not working properly

### ISSUE THREAD

**Issue by keeprock** [Aleksion/generator-angular-webpack-babel#7]
Hi.

I've added to app.config.js

```js
export default function config($locationProvider) {
    $locationProvider.html5Mode({
        enabled: true
    });
};
```

Then I try to access URL without hashbang I've got:

Cannot GET /URL

Installed package from [SO here](http://stackoverflow.com/questions/26904548/ui-router-returns-cannot-get-page) - still no luck.

It is something about webpack config?

Thanks!

**Comment by Aleksion** [comment]
Hi @hiason ,

are you testing the final version or the dev server?
I've never tried it with html5mode on the dev server, but it seems this might do the trick:
http://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option

Have you provided a base tag as well?:
https://docs.angularjs.org/error/$location/nobase

Let me know if this works out for you :)

**Comment by keeprock** [comment]
@Aleksion thanks for response. I'm using a base tag, as it stay there as a default setting.

I will take a look at link and give you a response if it will do the trick :) I guess that's the issue, especially I'm suspicious about webpack-dev-server. 

As I figured out - everything tied around dev server not being able to perform right actions.

**Comment by Aleksion** [comment]
Well it does make sense: When using htlm5 mode on ANY server, you need to have your server redirect http://HOSTNAME.com/login to index.html --> http://HOSTNAME.com/#/login
This setting is what makes that possible in webpack dev server
